-- MySQL Script generated by MySQL Workbench
-- Sun Oct 25 12:44:57 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shymotion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shymotion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shymotion` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `shymotion` ;

-- -----------------------------------------------------
-- Table `shymotion`.`instead_of_tweet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shymotion`.`instead_of_tweet` ;

CREATE TABLE IF NOT EXISTS `shymotion`.`instead_of_tweet` (
  `instead_of_tweet_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NOT NULL DEFAULT 0 COMMENT '',
  `body` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '',
  `secret_nick_name` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`instead_of_tweet_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shymotion`.`reply_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shymotion`.`reply_message` ;

CREATE TABLE IF NOT EXISTS `shymotion`.`reply_message` (
  `reply_message_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `instead_of_tweet_id` INT NOT NULL DEFAULT 0 COMMENT '',
  `body` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '',
  `secret_nick_name` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`reply_message_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shymotion`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shymotion`.`user` ;

CREATE TABLE IF NOT EXISTS `shymotion`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `twitter_user_id` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
